apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: mynamespace
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP  # Keeps it internal within the cluster

