apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: mynamespace 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: docker.io/library/frontend:latest
        imagePullPolicy: Never  
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_BACKEND_URL
          valueFrom:
            secretKeyRef:
              name: frontend-secret
              key: REACT_APP_BACKEND_URL

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: mynamespace
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31234
  type: NodePort  

